import type * as SQLite from 'expo-sqlite';

import type { LibraryGroup, SupplyCategory } from '@/types';

export type SeedGuide = {
  slug: string;
  title: string;
  category: string;
  libraryGroup: LibraryGroup;
  tags: string[];
  readingTime: number;
  offlineReady: number;
  priority: number;
  relatedTopics: string[];
  overview: string;
  steps: { title: string; detail?: string }[];
  supplies: string[];
  mistakes: string[];
  safetyNote: string;
};

export type SeedPlanTemplate = {
  title: string;
  type: string;
  summary: string;
  checklist: string[];
  suppliesNeeded: string[];
  planNotes: string;
};

export type SeedSupply = {
  name: string;
  category: SupplyCategory;
  subcategory: string;
  quantity: number;
  unit: string;
  dailyUse: number;
  targetAmount: number;
  restockPriority: 'low' | 'normal' | 'high' | 'urgent';
  notes: string | null;
};

export function getSeedGuides(): SeedGuide[] {
  return [
    {
      slug: 'power-first-10',
      title: 'First 10 minutes of a power outage',
      category: 'Power',
      libraryGroup: 'emergency',
      tags: ['power', 'outage', 'safety'],
      readingTime: 4,
      offlineReady: 1,
      priority: 10,
      relatedTopics: ['long-power-loss', 'cooking-without-power'],
      overview: 'Stabilize light, preserve food temperature, and protect devices.',
      steps: [
        { title: 'Confirm scope', detail: 'Check breakers and neighbors if safe.' },
        { title: 'Light', detail: 'Use flashlights; avoid candles near flammables.' },
        { title: 'Fridge', detail: 'Keep doors closed; food stays cold for hours if sealed.' },
      ],
      supplies: ['Flashlight', 'Power bank', 'Battery radio'],
      mistakes: ['Opening freezer repeatedly', 'Using generators indoors'],
      safetyNote: 'Never run generators or grills indoors — carbon monoxide kills.',
    },
    {
      slug: 'water-drinking-safety',
      title: 'Water outage: drinking safety',
      category: 'Water',
      libraryGroup: 'emergency',
      tags: ['water', 'drinking', 'hygiene'],
      readingTime: 5,
      offlineReady: 1,
      priority: 10,
      relatedTopics: ['water-contamination', 'rainwater-basics'],
      overview: 'Prioritize drinking water and reduce non-essential use.',
      steps: [
        { title: 'Drinking', detail: 'Use sealed bottled water first.' },
        { title: 'Hygiene', detail: 'Hand sanitizer for hands; reserve water for drinking if scarce.' },
        { title: 'Listen', detail: 'Follow boil-water advisories from authorities.' },
      ],
      supplies: ['Bottled water', 'Wipes', 'Buckets'],
      mistakes: ['Drinking flood water', 'Ignoring boil notices'],
      safetyNote: 'When in doubt, use bottled or treated water for drinking.',
    },
    {
      slug: 'water-contamination',
      title: 'Suspected water contamination',
      category: 'Water',
      libraryGroup: 'emergency',
      tags: ['water', 'contamination', 'boil'],
      readingTime: 5,
      offlineReady: 1,
      priority: 9,
      relatedTopics: ['water-drinking-safety'],
      overview: 'Assume water is unsafe until officials clear it or you treat it properly.',
      steps: [
        { title: 'Stop use', detail: 'Switch to sealed bottled or treated water for drinking and brushing teeth.' },
        { title: 'Boil or filter', detail: 'Follow official guidance; boiling kills many pathogens when ordered.' },
        { title: 'Conserve', detail: 'Use wipes for cleaning; prioritize drinking and cooking.' },
      ],
      supplies: ['Bottled water', 'Bleach (unscented, label-read)', 'Filters rated for pathogens if available'],
      mistakes: ['Trusting cloudy or odorous tap water', 'Giving untreated water to infants'],
      safetyNote: 'Follow local advisories; chemical contamination may not be fixed by boiling alone.',
    },
    {
      slug: 'evacuation-go-bag',
      title: 'Evacuation go-bag checklist',
      category: 'Evacuation',
      libraryGroup: 'emergency',
      tags: ['evacuation', 'go-bag', 'documents'],
      readingTime: 6,
      offlineReady: 1,
      priority: 10,
      relatedTopics: ['shelter-in-place'],
      overview: 'Leave fast with IDs, meds, and a way to charge your phone.',
      steps: [
        { title: 'IDs & cash', detail: 'Wallet, cards, small cash.' },
        { title: 'Meds', detail: '7-day supply if possible; list of prescriptions.' },
        { title: 'Charge', detail: 'Phone, cable, power bank.' },
      ],
      supplies: ['Backpack', 'Water bottles', 'First aid'],
      mistakes: ['Delaying to pack non-essentials', 'Forgetting chargers'],
      safetyNote: 'If ordered to evacuate, go — roads may clog quickly.',
    },
    {
      slug: 'shelter-in-place',
      title: 'Shelter in place basics',
      category: 'Shelter',
      libraryGroup: 'emergency',
      tags: ['shelter', 'stay-home', 'hazmat'],
      readingTime: 6,
      offlineReady: 1,
      priority: 8,
      relatedTopics: ['severe-weather', 'sanitation-basics'],
      overview: 'Seal the space, stay informed, and conserve essentials when staying inside is safest.',
      steps: [
        { title: 'Rooms', detail: 'Pick an interior room with few windows; bring radio and phone.' },
        { title: 'Air', detail: 'Close windows and dampers; turn off HVAC if advised.' },
        { title: 'Comms', detail: 'Text when possible; conserve battery for check-ins.' },
      ],
      supplies: ['Battery radio', 'Plastic sheeting', 'Tape', 'Water'],
      mistakes: ['Opening doors to “check” outside smoke or chemical haze'],
      safetyNote: 'Follow reverse-911 and official instructions for your area.',
    },
    {
      slug: 'first-aid-essentials',
      title: 'First aid essentials (non-professional)',
      category: 'Medical',
      libraryGroup: 'emergency',
      tags: ['first aid', 'medical', 'bleeding'],
      readingTime: 7,
      offlineReady: 1,
      priority: 9,
      relatedTopics: ['medicine-shortage'],
      overview: 'Bleeding, breathing, and shock basics while help is on the way.',
      steps: [
        { title: 'Call help', detail: 'Emergency services when life-threatening.' },
        { title: 'Bleeding', detail: 'Direct pressure; elevate if trained and appropriate.' },
        { title: 'Airway', detail: 'Do not give food or drink to someone who may need surgery.' },
      ],
      supplies: ['Gloves', 'Sterile gauze', 'Bandages'],
      mistakes: ['Moving someone with spinal injury unnecessarily'],
      safetyNote: 'Training beats improvisation — take a certified first aid course when you can.',
    },
    {
      slug: 'sanitation-basics',
      title: 'Sanitation when water is scarce',
      category: 'Sanitation',
      libraryGroup: 'emergency',
      tags: ['sanitation', 'hygiene', 'water'],
      readingTime: 6,
      offlineReady: 1,
      priority: 8,
      relatedTopics: ['water-drinking-safety'],
      overview: 'Reduce disease risk with hand hygiene and safe waste handling.',
      steps: [
        { title: 'Hands', detail: 'Sanitizer or treated water for handwashing when tap water is suspect.' },
        { title: 'Toilet', detail: 'Line bucket with bag if flush fails; seal waste securely.' },
        { title: 'Trash', detail: 'Separate hygiene waste; keep flies away.' },
      ],
      supplies: ['Hand sanitizer', 'Trash bags', 'Bleach', 'Paper towels'],
      mistakes: ['Open wounds without clean hands'],
      safetyNote: 'Wash hands before eating and after bathroom use.',
    },
    {
      slug: 'severe-weather-room',
      title: 'Severe weather: safe room',
      category: 'Weather',
      libraryGroup: 'emergency',
      tags: ['weather', 'tornado', 'storm'],
      readingTime: 5,
      offlineReady: 1,
      priority: 8,
      relatedTopics: ['long-power-loss'],
      overview: 'Small interior room, lowest floor, away from glass.',
      steps: [
        { title: 'Position', detail: 'Basement or small interior room on lowest floor.' },
        { title: 'Cover', detail: 'Helmet or thick blanket over head if debris risk.' },
        { title: 'Alerts', detail: 'NOAA radio or phone alerts on battery saver.' },
      ],
      supplies: ['Shoes', 'Helmet', 'Whistle', 'Flashlight'],
      mistakes: ['Standing near windows', 'Driving into flooded roads'],
      safetyNote: 'Mobile homes are especially unsafe in tornadoes — plan a sturdier shelter.',
    },
    {
      slug: 'long-power-loss',
      title: 'Multi-day power loss at home',
      category: 'Power',
      libraryGroup: 'emergency',
      tags: ['power', 'extended', 'food'],
      readingTime: 7,
      offlineReady: 1,
      priority: 9,
      relatedTopics: ['cooking-without-power', 'power-first-10'],
      overview: 'Food safety, light discipline, and safe heating or cooling choices.',
      steps: [
        { title: 'Fridge', detail: 'Keep closed; eat perishables first when safe.' },
        { title: 'Battery', detail: 'Airplane mode; short check-ins; dim screen.' },
        { title: 'Heat/cool', detail: 'Dress in layers; avoid unsafe indoor combustion.' },
      ],
      supplies: ['Cooler', 'Ice', 'Blankets', 'Battery bank'],
      mistakes: ['Using outdoor stoves indoors', 'Ignoring fridge time limits'],
      safetyNote: 'Generators outside, away from windows — CO risk.',
    },
    {
      slug: 'communication-blackout',
      title: 'When calls fail: SMS and check-ins',
      category: 'Comms',
      libraryGroup: 'emergency',
      tags: ['sms', 'network', 'battery'],
      readingTime: 4,
      offlineReady: 1,
      priority: 8,
      relatedTopics: [],
      overview: 'SMS often works when voice fails; batch messages to save battery.',
      steps: [
        { title: 'SMS', detail: 'Short status to one out-of-area contact as hub.' },
        { title: 'Battery', detail: 'Airplane mode between checks; lower brightness.' },
        { title: 'Meet point', detail: 'Agree in advance who coordinates family messages.' },
      ],
      supplies: ['Charged phone', 'Power bank', 'Paper contact list'],
      mistakes: ['Repeated failed call attempts draining battery'],
      safetyNote: 'Satellite messengers help in remote areas if you have one.',
    },
    {
      slug: 'grow-tomatoes',
      title: 'Growing tomatoes in containers',
      category: 'Garden',
      libraryGroup: 'self_reliance',
      tags: ['tomatoes', 'containers', 'food'],
      readingTime: 8,
      offlineReady: 1,
      priority: 5,
      relatedTopics: ['soil-basics', 'seed-starting'],
      overview: 'Sun, big pot, support, and steady water beat fancy gear.',
      steps: [
        { title: 'Light', detail: '6+ hours direct sun or brightest spot you have.' },
        { title: 'Pot', detail: 'Large container with drainage; quality potting mix.' },
        { title: 'Water', detail: 'Even moisture; avoid wetting leaves late in day.' },
      ],
      supplies: ['Large pot', 'Potting mix', 'Cage or stake', 'Tomato starts or seeds'],
      mistakes: ['Tiny pots that dry out instantly', 'Irregular watering causing blossom end rot'],
      safetyNote: 'Wash hands after soil contact; use labeled fertilizers.',
    },
    {
      slug: 'seed-starting',
      title: 'Seed starting indoors',
      category: 'Garden',
      libraryGroup: 'self_reliance',
      tags: ['seeds', 'seedlings', 'light'],
      readingTime: 7,
      offlineReady: 1,
      priority: 5,
      relatedTopics: ['grow-tomatoes', 'soil-basics'],
      overview: 'Clean mix, warmth for germination, then strong light.',
      steps: [
        { title: 'Trays', detail: 'Drainage holes; label varieties and dates.' },
        { title: 'Germination', detail: 'Follow packet depth; cover for humidity if needed.' },
        { title: 'Light', detail: 'Seedlings need bright light or they stretch weakly.' },
      ],
      supplies: ['Seed mix', 'Trays', 'Domes', 'Grow light or sunny window'],
      mistakes: ['Overwatering', 'Starting too early for your frost date'],
      safetyNote: 'Harden off gradually before transplanting outdoors.',
    },
    {
      slug: 'compost-basics',
      title: 'Compost basics',
      category: 'Garden',
      libraryGroup: 'self_reliance',
      tags: ['compost', 'soil', 'recycle'],
      readingTime: 6,
      offlineReady: 1,
      priority: 4,
      relatedTopics: ['soil-basics'],
      overview: 'Balance greens and browns, keep it moist, turn when you can.',
      steps: [
        { title: 'Browns', detail: 'Dry leaves, cardboard, straw for carbon.' },
        { title: 'Greens', detail: 'Kitchen scraps, coffee grounds for nitrogen.' },
        { title: 'Air', detail: 'Turn pile to reduce odor and speed breakdown.' },
      ],
      supplies: ['Bin or pile space', 'Pitchfork', 'Water'],
      mistakes: ['Meat/dairy in open piles', 'Too wet and smelly anaerobic mess'],
      safetyNote: 'Wash produce from compost-fed gardens; pets away from piles.',
    },
    {
      slug: 'soil-basics',
      title: 'Soil basics for small plots',
      category: 'Garden',
      libraryGroup: 'self_reliance',
      tags: ['soil', 'drainage', 'organic'],
      readingTime: 6,
      offlineReady: 1,
      priority: 4,
      relatedTopics: ['container-gardening'],
      overview: 'Drainage, organic matter, and simple pH awareness.',
      steps: [
        { title: 'Texture', detail: 'Sandy drains fast; clay holds water — amend accordingly.' },
        { title: 'Organic matter', detail: 'Compost improves both sand and clay.' },
        { title: 'Test', detail: 'Local extension tests help for serious food growing.' },
      ],
      supplies: ['Compost', 'Mulch', 'Simple pH kit optional'],
      mistakes: ['Tilling wet clay', 'Over-fertilizing'],
      safetyNote: 'Wear gloves; wash hands after soil work (soil-borne pathogens).',
    },
    {
      slug: 'container-gardening',
      title: 'Container gardening overview',
      category: 'Garden',
      libraryGroup: 'self_reliance',
      tags: ['containers', 'balcony', 'small space'],
      readingTime: 6,
      offlineReady: 1,
      priority: 4,
      relatedTopics: ['grow-tomatoes'],
      overview: 'Right-sized pots, drainage, and fertilizer for limited space.',
      steps: [
        { title: 'Drainage', detail: 'Holes and feet or saucers that do not drown roots.' },
        { title: 'Mix', detail: 'Potting mix — not garden soil alone in pots.' },
        { title: 'Feed', detail: 'Nutrients wash out; feed on schedule for heavy feeders.' },
      ],
      supplies: ['Pots', 'Potting mix', 'Fertilizer', 'Mulch surface optional'],
      mistakes: ['Root-bound never repotted', 'Same mix year after year'],
      safetyNote: 'Lift safely; wet pots are heavy.',
    },
    {
      slug: 'preserving-food',
      title: 'Preserving food: overview',
      category: 'Food preservation',
      libraryGroup: 'self_reliance',
      tags: ['canning', 'safety', 'pantry'],
      readingTime: 8,
      offlineReady: 1,
      priority: 6,
      relatedTopics: ['drying-food', 'stocking-pantry'],
      overview: 'Follow tested recipes for canning; botulism is real.',
      steps: [
        { title: 'High-acid', detail: 'Fruit jams and pickles use different rules than low-acid veg.' },
        { title: 'Pressure canning', detail: 'Required for most vegetables and meats.' },
        { title: 'Label', detail: 'Date and contents; rotate stock.' },
      ],
      supplies: ['Jars', 'Lids', 'Canner', 'Timer'],
      mistakes: ['Random internet recipes for low-acid foods', 'Bad seals'],
      safetyNote: 'Use USDA/extension guidance for shelf-stable low-acid foods.',
    },
    {
      slug: 'drying-food',
      title: 'Drying food basics',
      category: 'Food preservation',
      libraryGroup: 'self_reliance',
      tags: ['dehydrate', 'storage'],
      readingTime: 6,
      offlineReady: 1,
      priority: 5,
      relatedTopics: ['preserving-food'],
      overview: 'Low moisture stops spoilage; even airflow matters.',
      steps: [
        { title: 'Slice', detail: 'Uniform thickness dries evenly.' },
        { title: 'Heat/air', detail: 'Dehydrator, oven low, or sun in clean screened setups.' },
        { title: 'Store', detail: 'Airtight; check for moisture in jars.' },
      ],
      supplies: ['Dehydrator or oven', 'Airtight jars', 'Oxygen absorbers optional'],
      mistakes: ['Case hardening — dry outside, wet inside', 'Storing damp food'],
      safetyNote: 'Meat jerky needs time/temp guidance to reduce pathogens.',
    },
    {
      slug: 'cooking-without-power',
      title: 'Cooking without grid power',
      category: 'Kitchen',
      libraryGroup: 'self_reliance',
      tags: ['cooking', 'fuel', 'outdoor'],
      readingTime: 6,
      offlineReady: 1,
      priority: 7,
      relatedTopics: ['long-power-loss'],
      overview: 'Outdoor fuel, ventilation, and fire safety.',
      steps: [
        { title: 'Outdoor', detail: 'Camp stoves and grills outside only.' },
        { title: 'Fuel', detail: 'Store fuel away from heat; use what your device expects.' },
        { title: 'Menus', detail: 'One-pot meals; soak beans ahead to save fuel.' },
      ],
      supplies: ['Camp stove', 'Fuel', 'Lighter', 'Wind screen'],
      mistakes: ['Indoor charcoal or camp fuel', 'Unstable pot on wind'],
      safetyNote: 'Never burn treated wood or unknown chemicals on food flames.',
    },
    {
      slug: 'rainwater-basics',
      title: 'Rainwater collection basics',
      category: 'Water',
      libraryGroup: 'self_reliance',
      tags: ['rain', 'water', 'off-grid'],
      readingTime: 6,
      offlineReady: 1,
      priority: 5,
      relatedTopics: ['water-drinking-safety'],
      overview: 'Good for irrigation first; drinking needs proper treatment.',
      steps: [
        { title: 'Catchment', detail: 'Clean roof materials; first-flush diverter helps.' },
        { title: 'Storage', detail: 'Dark tank, sealed lids, no light for algae.' },
        { title: 'Use', detail: 'Irrigation is lowest risk; drinking needs filtration + disinfection plan.' },
      ],
      supplies: ['Barrels', 'Gutters', 'Screens', 'First-flush kit'],
      mistakes: ['Assuming rain is pure without roof contamination'],
      safetyNote: 'Follow local laws; treat drinking water appropriately.',
    },
    {
      slug: 'basic-repairs',
      title: 'Basic home repairs in shortages',
      category: 'Home',
      libraryGroup: 'self_reliance',
      tags: ['tools', 'tape', 'leaks'],
      readingTime: 5,
      offlineReady: 1,
      priority: 5,
      relatedTopics: [],
      overview: 'Stop damage first; temporary fixes buy time.',
      steps: [
        { title: 'Water', detail: 'Shutoff valve; bucket leaks; tape as temporary only.' },
        { title: 'Power', detail: 'Trip breakers if sparking; do not touch wet electrics.' },
        { title: 'Air', detail: 'Plastic and tape for broken windows in storms.' },
      ],
      supplies: ['Shutoff wrench', 'Tarp', 'Duct tape', 'Flashlight'],
      mistakes: ['Working on live wires wet', 'Improvised gas repairs'],
      safetyNote: 'Call pros for gas lines and major electrical work.',
    },
    {
      slug: 'cash-budget-shortage',
      title: 'Cash and budgeting under price pressure',
      category: 'Finance',
      libraryGroup: 'self_reliance',
      tags: ['cash', 'budget', 'inflation'],
      readingTime: 7,
      offlineReady: 1,
      priority: 6,
      relatedTopics: ['stocking-pantry'],
      overview: 'Small cash buffer, rotating staples, and cutting waste before panic buys.',
      steps: [
        { title: 'Cash', detail: 'Small bills for card/network outages.' },
        { title: 'List', detail: 'Buy to a list; reduce impulse when prices spike.' },
        { title: 'Substitute', detail: 'Beans, grains, seasonal veg over packaged convenience.' },
      ],
      supplies: ['Envelope budget or app offline notes', 'Price book'],
      mistakes: ['Panic hoarding perishables', 'No small change'],
      safetyNote: 'Secure cash at home like any valuable.',
    },
    {
      slug: 'stocking-pantry',
      title: 'Stocking a resilient pantry',
      category: 'Food',
      libraryGroup: 'self_reliance',
      tags: ['pantry', 'rotation', 'staples'],
      readingTime: 7,
      offlineReady: 1,
      priority: 7,
      relatedTopics: ['preserving-food', 'cash-budget-shortage'],
      overview: 'What you eat, rotated FIFO, with water to cook grains and legumes.',
      steps: [
        { title: 'Staples', detail: 'Rice, beans, oats, salt, oil, canned fish/tomatoes.' },
        { title: 'Rotation', detail: 'Eat oldest first; date with marker.' },
        { title: 'Cook', detail: 'Practice one-pot meals on your actual stove setup.' },
      ],
      supplies: ['Airtight containers', 'Can opener', 'Measuring cups'],
      mistakes: ['Buying unfamiliar foods you will not eat', 'No manual can opener'],
      safetyNote: 'Allergies and infant formula need individual planning.',
    },
    {
      slug: 'off-grid-basics',
      title: 'Off-grid basics (light, water, comms)',
      category: 'Off-grid',
      libraryGroup: 'self_reliance',
      tags: ['solar', 'water', 'radio'],
      readingTime: 8,
      offlineReady: 1,
      priority: 5,
      relatedTopics: ['long-power-loss', 'rainwater-basics'],
      overview: 'Layer small systems: light, water carry, and information.',
      steps: [
        { title: 'Light', detail: 'Solar lantern or panel + power station sized to phone + light.' },
        { title: 'Water', detail: 'Carry plan and filtration hierarchy for your sources.' },
        { title: 'Info', detail: 'NOAA radio; paper maps; neighbor agreements.' },
      ],
      supplies: ['Solar panel', 'Battery bank', 'Gravity filter', 'Radio'],
      mistakes: ['Undersized inverter', 'No maintenance plan for batteries'],
      safetyNote: 'Solar installs have electrical risks — follow manuals.',
    },
  ];
}

export function getPlanTemplates(): SeedPlanTemplate[] {
  return [
    {
      title: '7-day food shortage plan',
      type: 'Shortage',
      summary: 'Stretch staples, one meal pattern, and neighbor coordination for a week.',
      checklist: [
        'Inventory pantry and freezer; eat perishables first',
        'One simple daily meal theme to reduce decision fatigue',
        'Agree with household: water glasses only at meals if supply is tight',
        'Check on neighbors with kids or elders after day 2',
      ],
      suppliesNeeded: ['Rice or oats', 'Canned protein', 'Cooking oil', 'Salt'],
      planNotes: 'Adjust portions using your Supplies tab daily-use fields when set.',
    },
    {
      title: 'Water restriction plan',
      type: 'Water',
      summary: 'Prioritize drinking, cooking, and hygiene in that order.',
      checklist: [
        'Fill clean tubs/bottles immediately if outage is announced',
        'No half-load laundry; short showers',
        'Hand sanitizer for hands; reserve tap for drinking',
        'Track liters left vs household size',
      ],
      suppliesNeeded: ['Bottled water', 'Baby wipes', 'Buckets'],
      planNotes: 'Tie numbers to household profile water use per day.',
    },
    {
      title: 'Fuel shortage plan',
      type: 'Fuel',
      summary: 'Combine trips, keep tank rule, protect generator fuel storage.',
      checklist: [
        'Keep tank at least half if shortages are rumored',
        'One combined errand run per week if possible',
        'Store fuel only in proper containers, away from home living space',
        'Bike/walk plan for critical short trips',
      ],
      suppliesNeeded: ['Approved fuel cans', 'Siphon kit', 'Bike repair kit'],
      planNotes: 'Follow local fuel storage regulations.',
    },
    {
      title: 'Winter power outage plan',
      type: 'Weather',
      summary: 'Heat one room, safe backup heat, and pipe protection.',
      checklist: [
        'Move sleep to warmest interior room',
        'Drip faucets if needed to reduce pipe freeze risk',
        'Never use outdoor stoves or generators indoors',
        'Check elderly neighbors',
      ],
      suppliesNeeded: ['Blankets', 'Battery radio', 'Pipe insulation'],
      planNotes: 'Link to heating type in household profile.',
    },
    {
      title: 'Family communication plan',
      type: 'Comms',
      summary: 'One out-of-area contact, message templates, and meet points.',
      checklist: [
        'Pick an outside-region contact who relays messages',
        'Write SMS templates in app settings',
        'Two meet points: near home and farther rally point',
        'Test a family text thread monthly',
      ],
      suppliesNeeded: ['Paper contact list', 'Power banks'],
      planNotes: 'Add key people in Contacts tab.',
    },
    {
      title: 'Home lockdown / shelter plan',
      type: 'Safety',
      summary: 'When staying inside is safer than leaving.',
      checklist: [
        'Seal room supplies ready (plastic, tape, radio)',
        'Turn off HVAC only if advised',
        'Pets and carriers accessible',
        'Emergency numbers written large for kids',
      ],
      suppliesNeeded: ['Plastic sheeting', 'Tape', 'Battery radio'],
      planNotes: 'Pair with shelter-in-place guide in Library.',
    },
    {
      title: 'Garden prep plan',
      type: 'Self-reliance',
      summary: 'Small steps toward food growing even with limited space.',
      checklist: [
        'Inventory seeds and pots',
        'Set one sunny spot or grow-light shelf',
        'Start one easy crop this season',
        'Compost or soil amendment plan',
      ],
      suppliesNeeded: ['Seeds', 'Potting mix', 'Containers'],
      planNotes: 'Use Food growing supplies category.',
    },
    {
      title: 'Off-grid prep plan',
      type: 'Self-reliance',
      summary: 'Layer light, water, and information without the grid.',
      checklist: [
        'Test battery bank on real phone + light load',
        'Fill water stores; note liters per person',
        'Paper maps of area',
        'NOAA radio batteries replaced seasonally',
      ],
      suppliesNeeded: ['Solar panel', 'Battery bank', 'Water containers'],
      planNotes: 'Cross-check with Power category targets.',
    },
  ];
}

export function getDefaultSupplies(): SeedSupply[] {
  return [
    {
      name: 'Drinking water (stored)',
      category: 'Water',
      subcategory: 'Stored water',
      quantity: 12,
      unit: 'L (example)',
      dailyUse: 0,
      targetAmount: 20,
      restockPriority: 'high',
      notes: 'Adjust quantity to your containers; set dailyUse when you track liters/day.',
    },
    {
      name: 'Shelf-stable meals',
      category: 'Food',
      subcategory: 'Pantry',
      quantity: 10,
      unit: 'meals',
      dailyUse: 0,
      targetAmount: 21,
      restockPriority: 'normal',
      notes: 'Set dailyUse to household meals/day for clearer “days left”.',
    },
    {
      name: 'Power bank (phone)',
      category: 'Power',
      subcategory: 'Power banks',
      quantity: 1,
      unit: 'unit',
      dailyUse: 0,
      targetAmount: 2,
      restockPriority: 'high',
      notes: 'Charge monthly.',
    },
    {
      name: 'Flashlight',
      category: 'Home resilience',
      subcategory: 'Flashlight',
      quantity: 2,
      unit: 'units',
      dailyUse: 0,
      targetAmount: 2,
      restockPriority: 'normal',
      notes: 'Extra batteries in Power category.',
    },
    {
      name: 'Prescription buffer (days)',
      category: 'Medicine',
      subcategory: 'Prescriptions',
      quantity: 14,
      unit: 'days',
      dailyUse: 1,
      targetAmount: 30,
      restockPriority: 'urgent',
      notes: 'Not medical advice — discuss refills with your clinician.',
    },
  ];
}
